/**
 * UPI deep-link construction — Fulfillment & Subscriptions redesign,
 * Phase 5c (2026-09-03 payout redesign). The standard UPI intent URI
 * format ("upi://pay?pa=...") that every UPI app (GPay, PhonePe, Paytm,
 * BHIM, ...) already understands natively — not a Razorpay product, no
 * gateway involved, no cost, nothing to get approved. Built fresh at
 * payout time with the exact amount baked in, so scanning it in any UPI
 * app pre-fills both the payee and the amount — a seller's own uploaded
 * QR image (payoutMethodEnum's 'qr_image') can't do this, since it was
 * generated by her app before any amount was known. Rendering the actual
 * QR code image from this string happens client-side (see
 * lib/upi-qr-client.ts) using the same string this function returns.
 */
export function buildUpiDeepLink(params: {
  vpa: string;
  payeeName: string;
  amountRupees: number;
  note: string;
}): string {
  const query = new URLSearchParams({
    pa: params.vpa,
    pn: params.payeeName,
    am: params.amountRupees.toFixed(2),
    cu: 'INR',
    tn: params.note,
  });
  return `upi://pay?${query.toString()}`;
}
